### PR TITLE
💥 original file extension is now removed

### LINKED ISSUE #10: Remove old extension from converted file
- If the file is converted i am still having the old extension as the filename,

- for example the file that should be converted is example.dng, the output file will be named example.dng.jpg

I really appreciate the effort you put into the project

I will have a look into this issue

### PR DESCRIPTION
**Pull request by AgentSchmisch**
fixed #10

### CODE REVIEW

**Comment by AgentSchmisch** [comment]
I also added a feature to convert the files to another target path, if the target is not specified you can also use a flag to create a folder named 'converted' where the files will be stored
it is also possible to keep the files in the source directory

**Review by achimoraites — COMMENTED** [review]
Great work @AgentSchmisch !

I liked your code refactors and the fix!
Also, allowing the users to set their target directory is a cool addition!

Now you have also added the feature to select a target directory
there is a need to create that directory if it does not exist already.

In the previous implementation, the "converted" directory was set to be created if it did not exist; now that our users will be set to custom target, it would be nice to do that for their specified target folder.

**Comment by AgentSchmisch** [comment]
thanks, I think I overlooked that.😊

I added a argument that can be used to set, whether to create the folder converted or not.

If you have any applications that rely on the folder `converted`, I am happy to set that value to default `True`, just let me know

**Comment by achimoraites** [comment]
I think that makes sense to have a default folder to put the converted images and if the user sets a target directory we check if that directory exists and we create it if needed so the processed images can be stored there.

So far the "converted" has been the default.

**Comment by AgentSchmisch** [comment]
ok, I will implement the changes and push the project again 😊

The way it is implemented now is

for example using`raw-image-converter -s /source/directory -t /target/directory -f True`. That will create the folder `converted` inside `/target/directory` 

if you dont set the target and the -f argument it will do everything in the install directory of Python-Image converter
that is untested tho

**Comment by achimoraites** [comment]
Conflicts were addressed in a different PR

**Comment by achimoraites** [comment]
Great work @AgentSchmisch 👏 !!!

**Pull request closed without merging**
